name: Bug Report
description: Please let us know of any issues with Shuffle!
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting the problem. Please fill out the form below in detail.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: Platform
      description: What version of our software are you running?
      options:
        - Windows
        - Linux
        - MacOS
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: 어떤 버전의 Shuffle을 사용중이신가요?
      render: shell
  - type: textarea
    id: errors-txt
    attributes:
      label: Error Logs
      description: Please paste the contents of the .shuffle/errors.txt file.
      render: shell
