name: Report an issue
description: Please let us know of any issues with Shuffle!
title: ""
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting the problem. Please fill out the form below in detail.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: What type of problem is it?
      description: If you checked 'Other', please fill out the fields below.
      options:
        - Command Related
        - Automatic Completion (Command Suggestion)
        - Input Command (Typing)
        - Other
    validations:
      required: true
  - type: input
    id: type-other
    attributes:
      label: 'Other' type
      description: If you selected 'Other', please fill out
      render: shell
  - type: dropdown
    id: platforms
    attributes:
      label: Platform
      description: What version of our software are you running?
      options:
        - Windows
        - Linux
        - MacOS
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of Shuffle are you using?
      render: shell
  - type: textarea
    id: errors-txt
    attributes:
      label: Error Logs
      description: Please paste the contents of the .shuffle/errors.txt file.
      render: shell
