name: Build Shuffle

on:
  push:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    permissions: write-all
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - os: ubuntu-latest
          configure: ./vcpkg/bootstrap-vcpkg.sh
        - os: macos-latest
          configure: ./vcpkg/bootstrap-vcpkg.sh
        - os: windows-latest
          configure: .\vcpkg\bootstrap-vcpkg.bat

    steps:
    - uses: actions/checkout@v3
    
    - name: Update Submodule
      run: "git submodule update --init --recursive"
        
    - name: Download vcpkg
      run: git clone https://github.com/Microsoft/vcpkg.git
    - name: Configure vcpkg
      run: ${{ matrix.config.vcpkg_triplet }}
      
    - name: Install Packages
      run: "./vcpkg/vcpkg install jsoncpp curl kubazip"

    - name: Configure CMake
      run: cmake -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
      
    - name: Create version.h
      uses: 1arp/create-a-file-action@0.2
      with:
        path: "include"
        file: "version.h"
        content: "#define SHUFFLE_VERSION \"Beta 2.0\""

    - run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Upload Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        title: "Shuffle for Linux (${{ steps.date.outputs.date }})"
        automatic_release_tag: "linux/${{ steps.date.outputs.date }}"
        prerelease: true
        files: |
          build/bin/shuffle
          build/lib/libjsoncpp.so.25
          build/bin/${{env.BUILD_TYPE}}/shuffle.exe
          build/bin/${{env.BUILD_TYPE}}/jsoncpp.dll
          build/bin/shuffle
          build/lib/libjsoncpp.dylib
